version: '3.9'

services:
  webapp:
    build:
      context: ../../
      dockerfile: Docker/Dockerfiles/Dockerfile.webapp
    ports:
      - "5000:5000"
    environment:
      - MODEL_API_HOST=model
      - FLASK_ENV=development
      - IN_DOCKER=True
      - NVIDIA_VISIBLE_DEVICES=all   # 👈 Indispensable !
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    runtime: nvidia   # 👈 Ajoute ceci
