FROM python:3.12

####################
# SETUP DE BASE
####################

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY ./Docker/Requirements/requirements.txt /app/requirements.txt

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt


####################
# TÉLÉCHARGEMENT DES DONNÉES - PACK COMPLET
####################

# Télécharger le fichier zip complet
RUN wget https://github.com/Ayoub-Choukri/AIF_DATA/releases/download/RAG_Data/Data_Git.zip

# Dézipper le fichier (cela va créer le dossier Data/)
RUN unzip Data_Git.zip

# Supprimer le fichier zip
RUN rm Data_Git.zip





####################
# INSTALLATION D'OLLAMA
####################

# Mettre à jour la liste des paquets
RUN apt-get update

# Installer curl
RUN apt-get install -y curl

# Nettoyer le cache des paquets
RUN rm -rf /var/lib/apt/lists/*

# Télécharger le script d'installation d'Ollama
RUN curl -fsSL https://ollama.com/install.sh -o install_ollama.sh

# Exécuter le script d'installation d'Ollama
RUN sh install_ollama.sh

# Supprimer le script d'installation d'Ollama
RUN rm install_ollama.sh

# Installer le modèle Ollama llama3.1:8b
RUN ollama pull llama3.1:8b

# Installer le modèle Ollama llama3.2:1b
RUN ollama pull llama3.2:1b


####################
# COPIE DU CODE DE L'APPLICATION
####################

# Copy the rest of the application code into the container
COPY . /app

####################
# CONFIGURATION ET LANCEMENT DE L'APPLICATION
####################


# Expose the port the app runs on
EXPOSE 5000

# Set the environment variable for Flask
ENV FLASK_APP=app.py
ENV FLASK_ENV=development

# Run the application
CMD ["python","-u", "/app/Webapp/Api_Webapp_Files/Api_Webapp.py"]
