FROM python:3.12

####################
# SETUP DE BASE
####################

WORKDIR /app

COPY ./Docker/Requirements/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

####################
# TÉLÉCHARGEMENT DES DONNÉES - PACK COMPLET
####################

RUN wget https://github.com/Ayoub-Choukri/AIF_DATA/releases/download/RAG_Data/Data_Git.zip
RUN unzip Data_Git.zip
RUN rm Data_Git.zip

####################
# INSTALLATION D'OLLAMA
####################

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN curl -fsSL https://ollama.com/install.sh -o install_ollama.sh
RUN sh install_ollama.sh
RUN rm install_ollama.sh

# RUN ollama serve &


# # Pull des modèles
# RUN ollama pull llama3.1:8b
# RUN ollama pull llama3.2:1b
####################
# COPIE DU CODE ET SCRIPT ENTRYPOINT
####################

COPY . /app
COPY ./Docker/Entry_Points/Entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

####################
# CONFIGURATION ET LANCEMENT
####################

EXPOSE 5000

ENV FLASK_APP=app.py
ENV FLASK_ENV=development

CMD ["/bin/bash", "/app/entrypoint.sh"]
